[package]
name = "abc_357"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "../build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { workspace = true }

[build-dependencies]
docgen = { workspace = true }
